### ISSUE TITLE
Any plans for adding Jaws of the Lion Images?

### ISSUE THREAD

**Issue by solomojb** [any2cards/gloomhaven#10]
Hello,

 Just curious if there were any plans for adding images from any of the content of jaws of the lion?

Thanks,

**Comment by any2cards** [comment]
All of the JOTL cards were added a while ago.  They are within their own card viewer extension.

Here is a link to the repository: [JOTL Card Images](https://github.com/any2cards/jotl)

Here is a link to the Chrome extension: [JOTL Card Viewer Chrome Extension](https://chrome.google.com/webstore/detail/jotl-card-viewer/flinifpmhnobnjkdbdakehbokmiallkk)

Here is a link to the Firefox Add-On: [JOTL Card Viewer Firefox Add-On](https://addons.mozilla.org/en-US/firefox/addon/jotl-card-viewer/)

Here is a link to the JOTL Test Page: [JOTL Card Viewer Test Page](https://any2cards.github.io/jotl/)

**Comment by solomojb** [comment]
Awesome thank you.

Sent from my iPhone

On Jul 30, 2020, at 1:35 PM, William Habush <notifications@github.com> wrote:

﻿

All of the JOTL cards were added a while ago. They are within their own card viewer extension.

Here is a link to the repository: JOTL Card Images<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fany2cards%2Fjotl&data=02%7C01%7C%7C1fa410dc917b40f29a5608d834af047e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637317273576333904&sdata=WadhqyBf3RqjeZbevBkANwK9dsxosfji4tiUV2a%2B5xo%3D&reserved=0>

Here is a link to the Chrome extension: JOTL Card Viewer Chrome Extension<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fjotl-card-viewer%2Fflinifpmhnobnjkdbdakehbokmiallkk&data=02%7C01%7C%7C1fa410dc917b40f29a5608d834af047e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637317273576343905&sdata=rG2x2qeHZUqtDO5FLno3LuMKECkMeX1eZpaMu%2BsP8GE%3D&reserved=0>

Here is a link to the Firefox Add-On: JOTL Card Viewer Firefox Add-On<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faddons.mozilla.org%2Fen-US%2Ffirefox%2Faddon%2Fjotl-card-viewer%2F&data=02%7C01%7C%7C1fa410dc917b40f29a5608d834af047e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637317273576353893&sdata=C6jhYpYD3AWAoCNNlzNlzLCRDI262lHrg2KMdUn6tkI%3D&reserved=0>

Here is a link to the JOTL Test Page: JOTL Card Viewer Test Page<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fany2cards.github.io%2Fjotl%2F&data=02%7C01%7C%7C1fa410dc917b40f29a5608d834af047e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637317273576363887&sdata=YpzBORW7F4fqM5G5lleLSL8NHvdXxnROdzhLy8ByZK8%3D&reserved=0>
