### ISSUE TITLE
Doomstalker cards (at least) are inaccurate

### ISSUE THREAD

**Issue by kirk444** [any2cards/gloomhaven#11]
It appears that the doomstalker cards, as shown here, are from a pre-release version, and do not accurately reflect the printed copy of the game (either edition). The "Expose" card is the best example, it's missing the headline effect of "Advantage" for one attack on doomed enemies each turn.

**Comment by any2cards** [comment]
I appreciate you taking the time to notify me of this.  I am already aware of it, and have been for some time. I am working with Isaac and several members at Cephalofair to work on a permanent solution that will provide me complete access to all production assets for Gloomhaven and Frosthaven.  Obviously, there are very busy right now trying to finalize everything for Frosthaven. I reached out again today as a reminder, and hopefully I can get access to them soon.
