### ISSUE TITLE
Ability cards have reverted to First Edition on the latest commit

### ISSUE THREAD

**Issue by JulesLetters** [any2cards/gloomhaven#12]
Starting with commit 842f0cd, it seems come cards have been reverted to First Edition (CH's Avalache, card 118 is an example). commit fc7e641, before the October 2020 update, has the second edition cards.

https://github.com/any2cards/gloomhaven/blob/master/images/character-ability-cards/CH/avalanche.png

**Comment by any2cards** [comment]
Jules ... Thank you for your attention to detail, and for bringing this to my attention.  Unfortunately, I am ALL TOO aware of what has happened.  Lol.  I have been working with Isaac in getting a repository set up which will allow me to access the final Frosthaven assets when they become available.  As a test, we tested with the Gloomhaven assets.  Unfortunately, someone made a bad mistake and mixed in assets across the board from various iterations.  I am slowly working through this, by going class by class and reviewing all of the cards.  Bare with me, and in a few days, I should be posting a major update to fix things.

**Comment by any2cards** [comment]
I have not forgotten about this.  I am waiting for Cephalofair to provide the latest version of all GH character ability cards.  I do not want to revert to a previous commit due to some other issues with several of the classes.

**Comment by any2cards** [comment]
I received the 3rd Printing Gloomhaven Character Ability Cards from Cephalofair, and have implemented them for the GCV.  This issue should now be resolved.
