### ISSUE TITLE
Discrepancy with BS Attack Modifier Cards

### ISSUE THREAD

**Issue by ViciousChicken** [any2cards/gloomhaven#17]
The perk Attack Modifier cards for BS class don't all match with the PDF provided on the Cephalofair site for unlocking this class (and the character perk sheet here matches the PDF).  Minor details aside:
- The two Wound cards should also have +1.
- The two Poison cards should also have +1.
- There should only be one +2 Muddle (currently two)
- There should not be a +0

Reference: https://cephalofair.com/pages/bladeswarm

**Comment by any2cards** [comment]
Thank you very much for bringing this to my attention.  There have been 3 official versions of the BS character and their various assets.  Unfortunately, somehow, the attack modifiers were deprecated back to V1.  I am not sure how this happened.  I have fixed the attack modifiers, and will now have to look at the rest of the assets to make sure they are all correct for the BS character.
