### ISSUE TITLE
Adding empty battle goal front

### ISSUE THREAD

**Issue by signed** [any2cards/gloomhaven#18]
Hi, thank you for curating this repository.

[we](https://github.com/kosta/gloomhaven-stacks) used to pull in [gh-battle-goals-front](https://lh3.googleusercontent.com/u/0/d/19x3kdXZF2oEME3WipHeAXISfWkGtgmEA=w1440-h766-iv1) without text from the assets [published on google drive](https://drive.google.com/drive/folders/1bmklecSZO-cmxYxxi-udbxWGvFAH_iB-), but this recently stopped working.
Are you open to add it next to [gh-battle-goals-back](https://github.com/any2cards/gloomhaven/blob/master/images/battle-goals/gloomhaven/gh-battle-goals-back.png)?

**Comment by any2cards** [comment]
Are you asking me to host an empty (no-text) front battle goal card?  I have never done this before, so I don't know how you were getting it from my repo in the past.  The Google Drive you mention is NOT hosted by me.

**Comment by signed** [comment]
> Are you asking me to host an empty (no-text) front battle goal card?

Yes, the ask is to add this to your repository. I can prepare a PR if you want.

>  I have never done this before, so I don't know how you were getting it from my repo in the past

So far we pulled the card from google drive, not your repository
But this stopped working recently and we started to link to some cards here.
Before adding ``gh-battle-goals-front`` to our repo I reached out to you to add it here for others to find.

**Comment by any2cards** [comment]
While I am happy to host a blank card for you, I would need to make you are of two things:

1) I would need to acquire such an asset

2) I would not host it at this Gloomhaven repository as it will soon be deprecated (it will go away).  Once Firefox supports Manifest V3 (and some appropriate calls - which in theory should be withing 2 weeks), I will no longer need this repo, and everything will be leveraged from my Worldhaven repo.  So I would host your blank battle goal card there.

**Comment by signed** [comment]
> 1. I would need to acquire such an asset

> 3. Because I have now signed a license agreement with Cephalofair, I now have to ask them for permission to host templates such as this battle goal card.

As far as I know the blank battle goal card is part of the [``Creator Pack V2``](https://boardgamegeek.com/thread/1733586/files-creation)  that Isaac published under creative commons license BY-NC-SA 4.0. Could you acquire it from there?

> 2. I would not host it at this Gloomhaven repository as it will soon be deprecated (it will go away)

Thank you for the heads up. I'll look into the [worldhaven repository](https://github.com/any2cards/worldhaven)

**Comment by any2cards** [comment]
I have loaded the JPG files for both the front and back of the battle goal cards as they existed within the Creator V2 pack.  They have been stored here:

https://github.com/any2cards/worldhaven/tree/master/images/templates/gloomhaven

I am closing this ticket.
