### ISSUE TITLE
Add Project

### ISSUE THREAD

**Issue by stimm4711** [any2cards/gloomhaven#2]
Hi guys,

I wanted to let you know that I'm using the images of items, personal quests and events in the new version of my Gloomhaven Campaign Tracker Android app.

Project site: https://github.com/stimm4711/GloomhavenCampaignTracker
Playstore: https://play.google.com/store/apps/details?id=de.timmcode.ghcampaigntracker.droid

I made a fork to change some names and folders to make it easier to work with it.

Thank you very much for your effort and sharing the files!

**Comment by any2cards** [comment]
You are most welcome.  Good luck with your app !
