### ISSUE TITLE
overlay-token sizing is irregular.

### ISSUE THREAD

**Issue by Fyren** [any2cards/gloomhaven#3]
It seems like the sizing of the images `images/overlay-sizing/` is irregular.  

It seems like hexes are either a "thing" with a translucency instead of the floor or are a "floor" where it's filled in. For single hexes, floors are 539x478 and things are 469x421.  Double hexes are 539x869 and 469x811.  

But there are some images that are single hexes that fit none of those sizes:

- hazardous-terrain/hot-coals.png 539x498 (should be 539x478?)
- obstacles/altar.png 453x469 (should be 469x421?)
- obstacles/dark-pit.png 550x900 (should be 539x869?)
- treasures/treasure.png 500x425 (should be 469x421?) - this image is also weird, seems covered up with yellow on the top part

There's only two triple hexes, so I'm not sure on how they should be sized, but this one seems wrong:

- obstacles/boulder-3.png 805x813 (should be the same height as double hex things, so 811 pixels tall?)

Also, where did these come from?  I think I've seen open door images somewhere (as well as some others like at least triple hot coals)?

**Comment by any2cards** [comment]
These images can from Isaac's provided assets file and are provided as is.  I made no attempt to make them of a uniform size, nor did I state these were the only ones available for a overlay type.  I simply was showing examples of each type of overlay.
