### ISSUE TITLE
No enhancement stickers

### ISSUE THREAD

**Issue by lcruz4** [any2cards/gloomhaven#4]
Excellent resource, but I can't seem to find enhancement stickers

**Comment by any2cards** [comment]
I am a bit confused.  What exactly are you looking for?  A PNG file of the enhancements sticker sheet? Remember, the purpose of the GCV is to display in-line card images for discussions within forum threads.

**Comment by lcruz4** [comment]
Yea I was looking for the individual images of the enhancement stickers.
Such as +1, jump, etc.

I didn't realize the purpose sorry about that. Just figured it was a
collection of all images for the game.

I've found them elsewhere but not that good quality unfortunately

**Comment by any2cards** [comment]
Luis ...
No worries. I have many of the original digital assets for the game.  Let me take a look and see what I come up with.  If I can find them, I will place them in my drop box and send you a link.
This may not happened until tomorrow morning.
Will
    On Tuesday, October 29, 2019, 07:20:54 PM PDT, Luis Cruz <notifications@github.com> wrote:  
 
 Yea I was looking for the individual images of the enhancement stickers.
Such as +1, jump, etc.

I didn't realize the purpose sorry about that. Just figured it was a
collection of all images for the game.

I've found them elsewhere but not that good quality unfortunately

**Comment by lcruz4** [comment]
Awesome! That would be great. Whenever you have time, no rush

**Comment by any2cards** [comment]
Luis ...
Below, you will find a link to my DropBox for Gloomhaven.  For some reason, I did not have a +1 original digital asset.  I made one using the Gloomhaven Pirata One font, but unfortunately, it does not exactly match the actual enhancement sheets.
Not sure what font they used for it.  I will keep looking for it.  All of the others should be present in high resolution.
Let me know if this meets your needs.
Enhancements


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Enhancements

Shared with Dropbox
 |

 |

 |



Will
    On Tuesday, October 29, 2019, 07:51:02 PM PDT, Luis Cruz <notifications@github.com> wrote:  
 
 Awesome! That would be great. Whenever you have time, no rush

**Comment by lcruz4** [comment]
Hi Will,
Any chance I could get that dropbox link?

Btw it looks like these messages are getting automatically posted publicly
on github, so if you don't want to make the link public you can send the
link directly to me at luiscruzgmu@gmail.com

On Wed, Oct 30, 2019 at 11:30 AM Luis Cruz <lcruz4@gmu.edu> wrote:

> Hi Will,
>
> I'm not seeing a link to Dropbox in that last email.
>
> Appreciate your help
>
> On Tue, Oct 29, 2019, 11:11 PM any2cards <notifications@github.com> wrote:
>
>> Luis ...
>> Below, you will find a link to my DropBox for Gloomhaven.  For some
>> reason, I did not have a +1 original digital asset.  I made one using the
>> Gloomhaven Pirata One font, but unfortunately, it does not exactly match
>> the actual enhancement sheets.
>> Not sure what font they used for it.  I will keep looking for it.  All of
>> the others should be present in high resolution.
>> Let me know if this meets your needs.
>> Enhancements
>>
>>
>> |
>> |
>> |
>> | | |
>>
>> |
>>
>> |
>> |
>> | |
>> Enhancements
>>
>> Shared with Dropbox
>> |
>>
>> |
>>
>> |
>>
>>
>>
>> Will
>> On Tuesday, October 29, 2019, 07:51:02 PM PDT, Luis Cruz <
>> notifications@github.com> wrote:
>>
>> Awesome! That would be great. Whenever you have time, no rush
>>
>> On Tue, Oct 29, 2019, 10:45 PM any2cards <notifications@github.com>
>> wrote:
>>
>> > Luis ...
>> > No worries. I have many of the original digital assets for the game. Let
>> > me take a look and see what I come up with. If I can find them, I will
>> > place them in my drop box and send you a link.
>> > This may not happened until tomorrow morning.
>> > Will
>> > On Tuesday, October 29, 2019, 07:20:54 PM PDT, Luis Cruz <
>> > notifications@github.com> wrote:
>> >
>> > Yea I was looking for the individual images of the enhancement stickers.
>> > Such as +1, jump, etc.
>> >
>> > I didn't realize the purpose sorry about that. Just figured it was a
>> > collection of all images for the game.
>> >
>> > I've found them elsewhere but not that good quality unfortunately
>> >
>> > On Tue, Oct 29, 2019, 10:12 PM any2cards <notifications@github.com>
>> wrote:
>> >
>> > > I am a bit confused. What exactly are you looking for? A PNG file of
>> the
>> > > enhancements sticker sheet? Remember, the purpose of the GCV is to
>> > display
>> > > in-line card images for discussions within forum threads.
>> > >
>> > > —
>> > > You are receiving this because you authored the thread.
>> > > Reply to this email directly, view it on GitHub
>> > > <
>> >
>> https://secure-web.cisco.com/1vUyJTDtq5_Y4nvkjUXWPoxx1_7-ULM9eMn_YZ8GGrlhHco2YVp1oA4mVQglWG-yAaupDwCh8WAJ3AJYLOW3gurrjDpbPqzC0wxgNFK3gKL1Zw2LGB3wGDISpXTl7401g5qpYklmXQOVU0UVvji4kU4FWRZMEDt7rqYId1eqOaClbAujEKqYeMMIqF_rx2amft-aAf_It2iMkVYP9TFQ7Nj6tApaNT9OUi49AHZypuTqM_2J6h81WZKbSytHammIQiodiFXhjjZdiNStwsIbUKLUmzHuIFWBwvTtdkxrYx_g9EkP4J6Fe6F7wfU7RLlSdYYvpohmFnPEZdvx1zysSPuSzXK31W41--M4wMwYFsagT9LOf6ainZySsCQ52tgaRrbGau3P-aXc3cFABOPYA1SHesLYoF1d_jpHyPPrJtFkoSU9PSWDNL9yym6Wws8q7/https%3A%2F%2Fgithub.com%2Fany2cards%2Fgloomhaven%2Fissues%2F4%3Femail_source%3Dnotifications%26email_token%3DACCPROSIUCJK73WN5TZMQALQRDURLA5CNFSM4JGLTTHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECSV3GQ%23issuecomment-547708314
>> > >,
>> > > or unsubscribe
>> > > <
>> >
>> https://secure-web.cisco.com/1k0fbCHIIzTlbNcJ!%2065WCgP0Krfo3FD5Ktak0OE1pyUIcqgczrmhljCtSLHeCLhdqakwMGYwh2aRLzlcG9jV4INTNghtC-o67Q1QfbX4XRxuBEPv5QkMRZXcQhwmyEzfjBAmm6Wgf6aYQlazRqY2BJ1tYr2yzGpJ7LRUOPDV8cSQ_F7D7SCKDssGq1RiGVvMAk7IEvZfuRfZ6Cowl6oQTkHnfXtZvhnpPWd7rtHW1o5hIHf4Q_rn8EK8EYNBNfBl-s0dz8gbbzwm28Nf0RClPT4eIeq4wBsGHC24R4vMVDwaWhqVqneztrUs3z7IAbrc90VN-nw78MPTG3GLTjz2Pe12GYd2V02c4D2Ot0r-aETijdPkXDOKdiapSxG67zre4caUZRXor_nMptx8jm8KQng3cQ_6SMnTVfFhwUnEq8VN1TBWP-KoWzTfUKD6wCEa73/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACCPROUVR2SZQ7ZXCGT7JM3QRDURLANCNFSM4JGLTTHA
>> > >
>> > > .
>> > >
>> >
>> > —
>> > You are receiving this because you commented.
>> >
>> > Reply to this email directly, view it on GitHub, or unsubscribe.
>> >
>> > —
>> > You are receiving this because you authored the thread.
>> > Reply to this email directly, view it on GitHub
>> > <
>> https://secure-web.cisco.com/1CfQjKdJvpfBu-NW68jYF5IC4cLKofmDt1KPOvfNCO-o7M7V5Ah88u6Q6qZ0eHgbdKJLC0zbpBzdlpRPAPks8xWsM8E_Qz8uZvxQoTHYAWgNyS33A9yaQXyVgvUIr5K6_b0YxkGi6Gu4Yw3VR1H13dCa8wGW3wrQlDFq6smKtRFNphJnI4EZ0WzcnexzR7HLxq5s9-s35G-BlKWtE_fVNmIH7icJtndkbz8wvKNssWAkH3olLB-8Jzzc0w0ARU6xUNVBbxlUPTmr2C_--ACTNIBp3kgB-PIY8-uUTb4eEPDmbd-lyaAY8uzR4QvTZvbAmJbRWnX0OyL_fLaXQruonDOCtJTAOXYDa6OnaPyeQm8yY3sWbecC-Ypm2PHV7py2leBdCn3aL-71N5PJwe4NQ0Nd8QbcFnt3WvPdLOpczC3QbE27IAlytXBeSWxPpSKJ_/https%3A%2F%2Fgithub.com%2Fany2cards%2Fgloomhaven%2Fissues%2F4%3Femail_source%3Dnotifications%26email_token%3DACCPROWZ3IUFC5IWWQA4RL3QRDYMBA5CNFSM4JGLTTHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECSXQBQ%23issuecomment-547715078
>> >,
>> > or unsubscribe
>> > <
>> https://secure-web.cisco.com/12TOw6ET-T6VOq-fyg7fJihdkpzmAvh1cI9HcBxC95K7UVgLC0yQZc7srUC_SOtQxqeujZvRgoBBu4CijNDxDggC9WOwm9XdZZe8f1FBC4k1Ru5odnvwXfI7HoC8SIR3EQYYHdDaLd0PI1ESVnHDdjim-9Ca22JF0Pb99JqlQJOn_AyXv6wSZ4UVJhnekwU-TFAtxR_mg8Enw1N52lAxNsPDAhN6LeO27AfEvebS0guqOeDHBgaPTiZ89BlVxZ6rIXDrgaKeAvr8suw3ixJ5efjbbe9RiEgQKHGgsbYcg1U-3ASv2tquPJn0QPrwW8dZBDJ-4pQKVOimK_bnzW0-Bb4ydij2x8jqtMU5KLClOXE0ovW9kLwGtObeZv5KrD5ZKrbqKezgSthau3-Fo6t2rIVn0zMhU_KzztWX1TCyT8lpvezDUUXvWJf_Zg43OWAL3/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACCPROWIEHPVCC6YSY7IVJ3QRDYMBANCNFSM4JGLTTHA
>> >
>> > .
>> >
>>
>> —
>> You are receiving this because you commented.
>>
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://secure-web.cisco.com/1yi3gAVcCR7AujVHblxI1rE8EFTdsdSH3RG6DDHmZc_1qwSStnrxIpSh3_YOQitxdN4bEyL0elcXmy8vblEjtujw6aSKQnAFoahfASArKH1BrHOEByOAgZQ8bamyblUMPhCMiFIbpgZ6S5n3ZNhDrAamytJOecXvXHyXMHPDYdPgsW4NYyulyhgjHNZzrWjqud9SHGrk2IVOJ1mZTUgLBMwN0pR4oLTq2p50j3M8EvUTBtXwrTd10aUl3LlYa0BxvhmrWVnsVpyyeeP8vssISeOMjHwikXuvCTEUUYm_zGxx1cVRnDgCJSnXvbAM7QN4UrsOW8AUDT8i-iDml8mAPnufSs-qMi6ySG-udshe8NtQwr44T7BJQ-Jx3LB3so6BU/https%3A%2F%2Fgithub.com%2Fany2cards%2Fgloomhaven%2Fissues%2F4%3Femail_source%3Dnotifications%26email_token%3DACCPROQENXLCG43E54JR53DQRD3O5A5CNFSM4JGLTTHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECSY3GQ%23issuecomment-547720602>,
>> or unsubscribe
>> <https://secure-web.cisco.com/1LE6Bv9pT5JhNZ0iAC6KKUCDHLWakZRmPisAfMEyN55BU4dNfthLvO89bGHSDzqKd-NeRs9uWYDJkzgoG5qRiA5qQmnHfX_8fRwOWdpwFIwaXN3bSkR3LHHro97wV2cyTom9bSa_al9h0HAmNDtxkVA-fu5ozakr3VBCrtnAAQBhMDGKUTehEzumrMvOwPxK4EDRir28uUZty529VlIZYMJFgvmZ3zCv9dRNbW8EbI_dIMwSQaBeLK9WIqDOqk54kJidqz2PwuYJB5VMV_cJy5ABXNxx-3SmNEbZH5HaP_peioPPi7f4FXZ4y65DfpGu_SD0x3uVHsDi7fMNOCNcoJtMTBjtWHVegO8x3bQ7V6j6940kDC9qfTXmOc9lMxEJa/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACCPROUQRMW6ZA7XUA5IC4LQRD3O5ANCNFSM4JGLTTHA>
>> .
>>
>

-- 
Thanks,
-Luis Cruz

**Comment by any2cards** [comment]
I have contacted Luis directly via e-mail

**Comment by Sounour** [comment]
does this mean there will be no enhancement icons? Or is it hidden somewhere I didn't find it?

**Comment by any2cards** [comment]
I am not sure what you are commenting about, and/or asking about?  What enhancement icons are you looking for?

The purpose of this card viewer to to display the images of CARDS that come with Gloomhaven.

**Comment by Sounour** [comment]
Many of my cards already have enhancements, So to accurately display the cards I would have to have the enhancement icon for +1 or poison and stuff. 
What the paper version of Gloomhaven does with the stickers on the cards.

**Comment by any2cards** [comment]
Sebastian ...
The purpose of the Gloomhaven Card Viewer is to allow individuals, participating in forum threads and/or PBFs, to see an image of a card while they are discussing it.  It prevents them from having to dig the card out when other individuals are asking questions about a card, the interactions of a card's action and say an item, etc.
It is not meant to duplicate what your actual card that you are playing with looks like.

    On Monday, March 16, 2020, 03:00:54 PM PDT, Sebastian Osterbrink <notifications@github.com> wrote:  
 
 


Many of my cards already have enhancements, So to accurately display the cards I would have to have the enhancement icon for +1 or poison and stuff.
What the paper version of Gloomhaven does with the stickers on the cards.

**Comment by Sounour** [comment]
ok, in that case the line "You can use this data to build your own apps, etc." in the usage section should be modified. I read that as the purpose of this repo. But if I can't show enhanced cards I can't create a real deck of cards to play with.
