### ISSUE TITLE
Forgotten Circles Items

### ISSUE THREAD

**Issue by solomojb** [any2cards/gloomhaven#8]
Hello,

 I was wondering if there were plans of adding the FC items to the images/data?

Jim

**Comment by any2cards** [comment]
I am not certain what you are asking for here.  All of the Forgotten Circles cards are already added within the GCV repository.  For example, if you look under images\character-ability-cards, you will find DR, which contains all of the Diviner's character ability cards.  There is not a separate repository for Forgotten Circles, as it was an expansion for Gloomhaven.  As such, all of the cards can be found in the proper image subdirectories.

**Comment by solomojb** [comment]
I am looking for items greater than 151. I am helping modify gloomhaven item db which uses the images from your rep.

**Comment by any2cards** [comment]
They are there.  Under images\items.  Here is the direct path:

https://github.com/any2cards/gloomhaven/tree/master/images/items/152-165

**Comment by solomojb** [comment]
Ah i see what my problem is. The submodule doesnt point to the latest version. I see them now.  Thanks!

**Comment by any2cards** [comment]
Is is strange that this issue would exist, as these files were generated like 14 months ago.

**Comment by solomojb** [comment]
It's using a commit from March of 2019.

**Comment by any2cards** [comment]
Yes.  That would be a problem.  Lol

**Comment by solomojb** [comment]
LOl... well i guess the db project is a little behind. ;)

**Comment by any2cards** [comment]
I am closing this issue.  Good luck with your work.
