### ISSUE TITLE
Monster standee images

### ISSUE THREAD

**Issue by ericdepotter** [any2cards/gloomhaven#9]
Would it be possible to add images of the monster standees?

**Comment by any2cards** [comment]
I am not sure what "issue" this would solve?  By that I mean, what purpose would providing monster standees serve?  Are you asking for images of all of the monster standees for any given monster class (i.e. numbers 1 through 10 for the oozes)?  Are you just looking for art images?

I do not have images of the actual standees.  I do have art images in various forms for all of the monsters, and if you want those, I could simply share them directly with you.

I guess what I am trying to say is remember what the purpose of this tool is ... basically to display images of cards that are in the game, to facilitate easier and better communications within forums.

**Comment by ericdepotter** [comment]
I was not aware of the purpose of this tool. I thought this was a collection of all artwork of Gloomhaven. I have been looking for a clean collection of their art work (preferably with the shape of the standees, but not all numbers are necessary), so if you have them available, I would appreciate it if you can share them with me.

**Comment by any2cards** [comment]
Eric ... Here is a link to all of the original images for the monsters, from which the standees were created.  I hope this helps.

https://www.dropbox.com/sh/ldh41mms3fy8qie/AAC7XQIEcof9P9PwHKhO_iOaa?dl=0
